### ISSUE TITLE
[meta] 8.0 APM Server documentation updates

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#1023]
In 8.0, the default way of running Elastic APM will be with the APM integration.

**APM Guide updates**

- [x] Remove OSS artifact docs from the APM Server reference ([example](https://www.elastic.co/guide/en/apm/server/master/setup-repositories.html)) elastic/apm-server#6939
- [x] Deprecate `apm_oss` settings (still respected) ([example](https://www.elastic.co/guide/en/kibana/master/apm-settings-in-kibana.html)) related to https://github.com/elastic/kibana/issues/110733
- [x] Document upgrade order when APM Integration is installed via Kibana (https://github.com/elastic/apm-server/issues/5948)
- [ ] ~Deprecate standalone binaries in the docs ([example](https://www.elastic.co/guide/en/apm/server/master/setup-repositories.html))~
- [ ] ~Deprecate standalone binaries on marketing pages ([example](https://www.elastic.co/downloads/apm)) https://github.com/elastic/apm-server/issues/6060~

**Elastic Cloud updates**

- [x] Tracked in https://github.com/elastic/cloud/issues/95057
- [x] **NEW** Update Cloud settings ~(issue/details to follow from Silvia)~ Tracked in https://github.com/elastic/cloud/issues/96260
- [x] **NEW** More Cloud updates tracked in https://github.com/elastic/cloud/issues/96752

**Comment by bmorelli25** [comment]
@simitt to verify timeline

**Comment by simitt** [comment]
06/12/2021 Update:
* added some details related to cloud specific documentation
* removed deprecating work, as the APM Server standalone binary is not going to be deprecated yet

**Comment by bmorelli25** [comment]
@simitt A few 8.0 Cloud questions for you:

* Mode:
  * if stack version ≥8.0 --> Managed by Fleet mode
  * if stack version <8.0 --> Standalone in Cloud mode (can upgrade and remain in this mode)
* "APM & Fleet" user settings in Cloud. Are the following assumptions correct?
  * Managed by Fleet mode --> This will exist but doesn't do anything.
  * Standalone APM in Cloud mode --> This will exist and is used to configure APM.
* What about all of the `queue.*`, `setup.*`, etc., settings that are going away? How are these impacted by the "escape hatch" option of starting a 7.last deployment and upgrading to 8.x? Will these settings break upon upgrade?

**Comment by simitt** [comment]
> Mode:
> * if stack version ≥8.0 --> Managed by Fleet mode
> * if stack version <8.0 --> Standalone in Cloud mode (can upgrade and remain in this mode)

yes!

> "APM & Fleet" user settings in Cloud. Are the following assumptions correct?
> *  Managed by Fleet mode --> This will exist but doesn't do anything.

Afaik user settings should be hidden as soon as in managed mode (already in 7.x); @sarahetter can you confirm this?

> * Standalone APM in Cloud mode --> This will exist and is used to configure APM.

yes!

> What about all of the queue.*, setup.*, etc., settings that are going away? How are these impacted by the "escape hatch" option of starting a 7.last deployment and upgrading to 8.x? Will these settings break upon upgrade?

If users do upgrade without switching to managed mode, all settings that have previously be supported on cloud are still supported via the user overrides. 

> If my assumptions are correct, there are three different use cases for Edit APM user settings:

I'd say we have following scenarios:
* A user running an APM Server in managed mode: Will want the APM integration config docs in the APM Guide.
   This is the case for any new deployments >= 8.0 and any deployments where user manually switched from standalone to managed. 
* A user running an APM Server in standalone mode: Will want the Supported APM settings.
   This is the case for deployments created <= 8.0 (and potentially upgraded to >= 8.0) without users actively switching to managed mode.

**Comment by bmorelli25** [comment]
Thanks, Silvia!

> Afaik user settings should be hidden as soon as in managed mode (already in 7.x)

By "user settings", we're both talking about this, right?
<img width="798" alt="Screen Shot 2022-01-11 at 2 57 06 PM" src="https://user-images.githubusercontent.com/5618806/149034618-0cc38e51-422d-44c9-8eaf-a2b5cd4bea13.png">

I still see it when running managed mode in 7.16.2. And I'm pretty sure it was there when I was testing on 8.0.0-rc1 last week.

**Comment by simitt** [comment]
Yes, that's the settings. 
The user settings are shown if users actively migrated to managed mode, vs. they will be hidden for new deployments >= 8.0. IMO that's a bug and the user settings should always be hidden when running in migrated mode, but didn't get any confirmation on this being planned to be changed. Will follow up here once I know more.

**Comment by simitt** [comment]
@bmorelli25 I just realized that we do not have a specific tracking issue for describing the upgrade flow from `7.17` to`8.x` for on-prem and cloud. Is this covered already (implicitly) by any of the tasks you are working on or should I create a dedicated task and provide a specific description?

**Comment by bmorelli25** [comment]
I've had upgrading in the back of my mind, but a specific issue for `7.17 -> 8.x` linked to this 8.0 meta issue would be helpful.

For the 7.17 upgrading docs, I was thinking we could mostly (if not completely) reuse the [upgrading docs](https://www.elastic.co/guide/en/apm/guide/current/upgrade.html) put together for 7.16.

**Comment by bmorelli25** [comment]
@simitt can you clarify when you have some time. I'm confused about these two statements:

https://github.com/elastic/observability-docs/issues/1023#issuecomment-1008877338:

> > What about all of the queue., setup., etc., settings that are going away? How are these impacted by the "escape hatch" option of starting a 7.last deployment and upgrading to 8.x? Will these settings break upon upgrade?
>
> If users do upgrade without switching to managed mode, all settings that have previously be supported on cloud are still supported via the user overrides.

vs https://github.com/elastic/cloud/pull/95269/files#r786716269:

> 8.0 brings some breaking changes to supported settings, removing support for any kind of setup. These changes can be covered in a separate PR but just realized when going through this one.

**Comment by simitt** [comment]
Seems I blanked when providing this answer, apologies for that:
>>What about all of the queue., setup., etc., settings that are going away? How are these impacted by the "escape hatch" option of starting a 7.last deployment and upgrading to 8.x? Will these settings break upon upgrade?

>If users do upgrade without switching to managed mode, all settings that have previously be supported on cloud are still supported via the user overrides.

These options are not supported any more by APM Server, so they also cannot be supported any more in Cloud. We have missed to update the allowlisting though until now. I have to go through the settings in detail to be able to provide an overview of supported settings. Will follow up here.

**Comment by bmorelli25** [comment]
Great, thanks!

Also, no need for a specific upgrading to 8.0 issue. I'm working on that PR now.

**Comment by simitt** [comment]
Regarding the _Edit User Settings_ - the cloud team reopened an issue for this. It is not supposed to show in the UI when apm is migrated.

**Comment by bmorelli25** [comment]
The final batch of updates for Cloud are now merged (https://github.com/elastic/cloud/issues/96752). Closing this PR as I think we're finally done!
