### ISSUE TITLE
[meta] Improve standalone agent docs

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#1059]
## Description

The standalone agent is considered an advanced use case, but even advanced users need good docs. Let's use this issue to track existing requirements and discuss how we can improve the overall user experience with the standalone agent docs.

Related issues and PRs, organized by priority:

MVP (next):

- [x] https://github.com/elastic/observability-docs/issues/1084
- [x] https://github.com/elastic/observability-docs/issues/1030 PR: https://github.com/elastic/observability-docs/pull/1276
- [x] https://github.com/elastic/observability-docs/issues/749

Future:
- [x] https://github.com/elastic/observability-docs/issues/581
- [ ] https://github.com/elastic/beats/issues/23741
  https://github.com/elastic/observability-docs/pull/424 (in progress)
- [ ] https://github.com/elastic/beats/issues/23746
  https://github.com/elastic/observability-docs/pull/500 (in progress)

Done previously:
- [x] https://github.com/elastic/beats/issues/23742
  https://github.com/elastic/observability-docs/pull/460 (merged)

## Collaboration

* Other (please describe): docs team and product team will collaborate, with docs team taking the lead on task-based content and product team developing reference content.

**Contact Person:**

TBD

## Suggested Target Release

TBD

## Stakeholders

@elastic/obs-docs 
@mostlyjason 
@nimarezainia

**Comment by dedemorton** [comment]
Nothing here that I've made some improvements to the standalone docs during the TOC reorg: https://github.com/elastic/observability-docs/issues/784

**Comment by dedemorton** [comment]
We will track future improvements in a new meta issue. This one is getting old and stale.
