### ISSUE TITLE
[meta] Improve Fleet Server doc experience

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#1060]
## Description

We've documented the basic steps for users who need to deploy Fleet Server, but users need more guidance.

Related issues and PRs:

- [x] https://github.com/elastic/observability-docs/issues/642
PR in review: https://www.elastic.co/guide/en/fleet/current/fleet-server.html#fleet-server-configuration
- [x] https://github.com/elastic/observability-docs/issues/523 
  PR in review: https://github.com/elastic/observability-docs/pull/1061 
- [x] https://github.com/elastic/observability-docs/issues/1007
PR in review: https://github.com/elastic/observability-docs/pull/1091

## Collaboration

TBD

* [ ] The docs team will lead producing the content
* [x] The product team will provide the initial content and the docs team will edit / review
* [ ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

**Contact Person:**

TBD

## Suggested Target Release

TBD

## Stakeholders

@elastic/obs-docs 
@mostlyjason 
@nimarezainia

**Comment by dedemorton** [comment]
Closing because we've done all the tasks in the list. I'm not saying we shouldn't do more work, but let's come up with a new meta issue.
