### ISSUE TITLE
[Request] Create APM integration documentation

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#1073]
## Description

Create a new APM integration documentation book. This book should contain all APM Overview content and a new, legacy section for deprecated content.

### 7.16

**Move old content. Make easy updates. Stop building old docs.**

- [x] Move deprecated documentation to a legacy directory
  * https://github.com/elastic/apm-server/pull/6287
- [x] Add the `APM User Guide` to the doc build (incl attrs)
  * https://github.com/elastic/docs/pull/2246
  * https://github.com/elastic/docs/pull/2250
- [x] Move APM Overview content to the APM guide
  * https://github.com/elastic/apm-server/pull/6378
- [x] Move APM Server Reference content to the APM guide
  * https://github.com/elastic/apm-server/pull/6378
  * https://github.com/elastic/apm-server/pull/6427
- [x] Duplicate Stack Overview includes to `APM User Guide`
  * https://github.com/elastic/stack-docs/pull/1850
- [x] Open PRs to fix all broken links (list) https://github.com/elastic/docs/pull/2239#issue-1015739797
  * https://github.com/elastic/beats/pull/28519
  * https://github.com/elastic/stack-docs/pull/1850
  * https://github.com/elastic/elasticsearch/pull/79411
  * https://github.com/elastic/observability-docs/pull/1181
  * https://github.com/elastic/kibana/pull/115642
  * https://github.com/elastic/kibana/pull/115664
  * https://github.com/elastic/ecs/pull/1631
  * https://github.com/elastic/kibana/pull/116529
  * https://github.com/elastic/apm-server/pull/6477
- [x] Stop building the APM Server Reference and APM Overview
  * https://github.com/elastic/docs/pull/2239
- [x] Simulate bump to 7.16 (with an elastic/docs PR) and open issues to fix all broken APM agent links: https://github.com/elastic/docs/pull/2276
  * Go https://github.com/elastic/observability-docs/issues/1214
  * iOS https://github.com/elastic/observability-docs/issues/1222
  * Java https://github.com/elastic/observability-docs/issues/1216
  * .NET https://github.com/elastic/observability-docs/issues/1215
  * Node.js https://github.com/elastic/observability-docs/issues/1217
  * PHP https://github.com/elastic/observability-docs/issues/1218
  * Python https://github.com/elastic/observability-docs/issues/1219
  * Ruby https://github.com/elastic/observability-docs/issues/1220
  * RUM https://github.com/elastic/observability-docs/issues/1221

**Additional content improvements**

- [x] https://github.com/elastic/observability-docs/issues/1223
- [x] https://github.com/elastic/observability-docs/issues/1224
- [x] https://github.com/elastic/observability-docs/issues/1225
~- [ ] https://github.com/elastic/observability-docs/issues/1226~ Moved to 8.0
~- [ ] https://github.com/elastic/observability-docs/issues/1227~ Moved to 8.0
~- [ ] https://github.com/elastic/observability-docs/issues/1228~ Moved to 8.0
- [x] https://github.com/elastic/observability-docs/issues/1229
- [x] https://github.com/elastic/apm-server/issues/6433
- [x] ~https://github.com/elastic/observability-docs/issues/1213~ Moved to a future iteration
- [x] https://github.com/elastic/observability-docs/issues/1231
- [x] Remove all temp files
- [x] Remove old ES `ifeval` https://github.com/elastic/elasticsearch/blame/master/docs/Versions.asciidoc#L72 https://github.com/elastic/elasticsearch/pull/81402
- [x] Fix broken obs docs includes
- [x] Request redirects for APM Server Reference and APM Overview `master`, `8.0`, and `7.16`
  * https://github.com/elastic/website-development/issues/8388
- [x] Add deprecation notices to legacy docs: https://github.com/elastic/apm-server/pull/6708
- [x] Add upgrading guide https://github.com/elastic/apm-server/pull/6709
- [x] Move APM Server Reference and APM Overview to Legacy docs https://github.com/elastic/docs/pull/2309
- [x] Add banner to 7.15 docs https://github.com/elastic/apm-server/pull/6833

### After release
- [x] Fix link to APM Guide in the ECS docs: https://github.com/elastic/ecs/pull/1710
- [x] https://github.com/elastic/observability-docs/issues/1285

### If I have time
~- [ ] https://github.com/elastic/observability-docs/issues/1288~ Moved to 8.0

## Suggested Target Release

7.16

## Stakeholders

@simitt @bmorelli25

**Comment by bmorelli25** [comment]
Nearly all tasks for this issue have been completed. Of the four remaining issues, three have fallen to 8.0, and one has an unknown completion date. A summary is below. I'm going to (finally) close this as we have new tracking issues for 8.0.

Moved to 8.0:
- https://github.com/elastic/observability-docs/issues/1226
- https://github.com/elastic/observability-docs/issues/1227
- https://github.com/elastic/observability-docs/issues/1228

Moved to backlog:
- https://github.com/elastic/observability-docs/issues/1213 (unknown completion date)
