### ISSUE TITLE
[meta] Update documentation to show unified integrations view

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#1185]
## Description

Starting in 7.16, the integrations view is changing and will include cards for Beats and other technologies (not just Elastic Agent integrations). We need to update the docs to reflect this change.

Related issue: https://github.com/elastic/docs.elastic.co/issues/1

## Collaboration

* [x] The docs team will lead producing the content
* [ ] The product team will provide the initial content and the docs team will edit / review
* [ ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

**Contact Person:**

@goodroot 

## Suggested Target Release

7.16

**Comment by dedemorton** [comment]
I think we've made the terminology and related content changes that are required to the Fleet and Elastic Agent docs, but we might want to mention the unified view in the quick start to help users avoid confusion when they're getting started. So I'll keep this open and move it to the to-do col.
