### ISSUE TITLE
[Meta] Migrate processor documentation to Elastic Agent

### ISSUE THREAD

**Issue by ph** [elastic/observability-docs#1376]
## Summary (updated by @dedemorton):

This issue has been stalled for a variety of reasons (not worth detailing here).

Here's the plan for moving this work forward:

- [x] Revive #500 (rebase and resolve conflicts).
- [x] Move processors to top level in the hierarchy.
- [x] Improve introduction:
  - [x] Explain all the places where you can define processors (like in the UI when you configure the integration, in the standalone config file, etc) and explain how the syntax differs.
  - [x] Create a topic that covers the syntax.
- [x] Do a side-by-side compare to check for changes in Beats (new processors, changed processors, etc)
- [x] Ask development team to identify any processors that should not be documented for Elastic Agent.
- [x] Add any processors that are missing (except the ones listed above).
- [x] Change the directory structure to move processors up in the directory and rename files for consistency.
- [x] Edit the docs for the new processors. (The edits will not be made to the Beats source, just Elastic Agent.)
  - [x] Decide whether to fix inconsistency in how settings are presented (list vs table format). Looks like the processors defined in ingest pipelines use tables, so maybe it makes more sense to use that format here, too? However sometimes tables that contain long names end up with weird line wraps.
  - [x] Make all processor topics consistent in structure.
  - [x] Apply copy edits to fix inconsistencies in common setting descriptions.
- [x] Decide whether to convert the content to Markdown (next docs) or keep it in asciidoc (current docs system). Decision: Keeping in asciidoc to get it published faster; will migrate to Markdown along with other docs.
- [x] If we decide to keep it in asciidoc, add a new section to the Fleet/Agent Guide called "Define processors" at the top level (top level makes sense because you can define processors in multiple places: integrations config, standalone agent config, etc).
- [x] Add the rest of the processors listed in #500.

Remaining todo items:

- [x] Open review.
- [x] Ask development team if we need to add any notes/warnings that explains additional steps the user might need to take. For example, if you use a processor to add fields, do you need to adjust the ingest pipeline so the field gets ingested?
- [x] Move SSL options to a separate topic (outside of the output docs) and link to the relevant sections from all the reference topics where SSL options can be set.
- [x] Make sure the [diagram in the add data topic](https://www.elastic.co/guide/en/cloud/current/ec-cloud-ingest-data.html#ec-data-ingest-pipeline) is updated after this content is merged. PR is up here: https://github.com/elastic/cloud/pull/111202
- [x] Make sure links in integrations/fleet get updated. Created https://github.com/elastic/integrations/issues/4989 to track.

Note that I've removed the old list and description because it was very old and the details were no longer accurate. See #500 for list of processors under consideration.

**Comment by joshdover** [comment]
@nimarezainia we need to coordinate with integrations to update their documentation link to point to these new docs instead of the filebeat ones. For example in the system integration:

<img width="422" alt="image" src="https://user-images.githubusercontent.com/1813008/211525091-37ccd5cc-c73f-41a8-a0fa-83378c111904.png">

**Comment by joshdover** [comment]
We can probably do a quick find a replace on the whole integrations repo

**Comment by dedemorton** [comment]
This auto-closed. I am re-opening because we have some follow-up tasks to track.

**Comment by dedemorton** [comment]
Closing now because I've opened issues to track related work.
