### ISSUE TITLE
APM documentation updates

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#1482]
An issue to track all of the APM documentation issues

### 7.17
- [x] https://github.com/elastic/observability-docs/issues/1385

### 8.0
- [x] https://github.com/elastic/observability-docs/issues/1023
- [x] https://github.com/elastic/observability-docs/issues/1073
- [x] https://github.com/elastic/apm-server/issues/6662
- [x] https://github.com/elastic/apm-server/issues/6446
- [x] https://github.com/elastic/apm-server/issues/5987
- [x] https://github.com/elastic/apm-server/issues/6423
- [x] https://github.com/elastic/apm-server/issues/6775
- [x] https://github.com/elastic/apm-server/pull/7202
- [x] Elastic Cloud BCs

### 8.1
- [x] https://github.com/elastic/apm-server/issues/4586
- [x] https://github.com/elastic/apm-server/issues/7073
- [ ] https://github.com/elastic/observability-docs/issues/1500
- [x] https://github.com/elastic/apm-server/issues/3569
- [x] https://github.com/elastic/apm-server/issues/7219
- [x] Attempt to fix 7.15 docs outranking 8.0 docs: https://github.com/elastic/apm-server/pull/7310

### Later
- [x] https://github.com/elastic/apm-server/issues/6844
- [x] https://github.com/elastic/apm-server/issues/6801
- [x] https://github.com/elastic/observability-docs/issues/1228 (no time yet)
- [x] https://github.com/elastic/apm-server/issues/5988 (removed from 8.0 due to bug—see issue for deets)
- [ ] https://github.com/elastic/observability-docs/issues/1226 (removed from 8.0 due to bug—see above issue for deets)

### Issues needed
- [x] Troubleshooting including APM integration

**Comment by bmorelli25** [comment]
This meta issue is mostly complete. There are two unfinished issues:

* https://github.com/elastic/observability-docs/issues/1500 ➡️ **Blocked with no current ETA.**
* https://github.com/elastic/observability-docs/issues/1226 ➡️ **Blocked. See the issue for ETA.**

Since the only remaining issues are blocked, I'm going to close this.
