### ISSUE TITLE
[meta] Automate integration documentation

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#1848]
## Problem

This issue explores two problems:

1. Integration `readme.mdx` files need to move out of [elastic/wordlake](https://github.com/elastic/integration-docs/issues/12). The project is maturing and it no longer makes sense to open PRs against a repo that is supposed to only contain published documentation.
3. Our manual integration documentation build process is tedious and lags too far behind the development/release process. There is no lint or check that current `readme.md` files work in the Elastic documentation build. In addition, a manual update process is required any time we want to update the documentation. 

### Solution

At this point, the best path forward seems to be exploring the idea of generating `readme.mdx` files when an Elastic package is built. This solution allows us to:
* Run PR checks ensuring changes to integration documentation will build in our documentation system.
* Automate the docs by removing a manual build step.
* Remove an extra source of data required (no more copying `readme.md` files to `readme.mdx` files).

### Issues

- [ ] https://github.com/elastic/integrations/issues/3260
- [ ] https://github.com/elastic/integration-docs/issues/12
- [ ] https://github.com/elastic/elastic-package/issues/805 Add the docsmobile build as a ci check to repositories with integrations
  * elastic/integrations
  * elastic/apm-server/apmpackage/
  * others?
- [ ] Pull `readme.mdx` files into elastic/wordlake
- [ ] Remove scripts from elastic/wordlake

### Related

If we decide not to move forward with `.mdx` files by default, then we'll need some kind of integrations lint feature to ensure chars like `<`, `>`, `{`, and `}` aren't merged into files.

### Open questions

* Currently, our integration documentation is built from the production endpoint of the EPR API. How will this process change that? Do we want to publish docs when a change to an integration is merged? Or should we continue to use the EPR API and instead run a script every x hours that pulls `readme.mdx` files from the EPR API and publishes them to elastic/wordlake?

### Stakeholders

* @akshay-saraswat 
* @mtojek 
* @goodroot 
* @bmorelli25

**Comment by bmorelli25** [comment]
@colleenmcginnis is working on improving the documentation of our top integrations. As she adds complexity to these docs, her PRs (like https://github.com/elastic/integrations/pull/3308) have shed light on inconsistencies between how Kibana interprets `.md` files and how docsmobile interprets `.mdx` files. These inconsistencies complicate our plan to build `.mdx` files by default.

#### **Links**

Files consumed by Kibana expect markdown style links: `[text](url)`. Our documentation build (docsmobile) accepts links of this style, but AFAIK for internal links, the build prefers the `DocLink` component: `<DocLink id="slug" />`.

@goodroot will internal links using markdown style syntax still be link checked?

#### **Docsmobile components**

In addition to links, we'll be unable to make use of all docsmobile components in package readme files as they're not interpreted by Kibana. I suppose we can work around this, but it's very limiting and unfortunate, especially for components like [badges](https://docs.elastic.dev/docs/syntax#badges) and [callouts](https://docs.elastic.dev/docs/syntax#doccallout).

#### **Comments**

* Markdown comment syntax: `<!-- Example ?? -->` (this breaks the docsmobile build)
* mdx comment syntax: `{/* I'm a comment */}` (this renders as text in markdown)

**Comment by goodroot** [comment]
@cchaos 👋 This has came up previously, checking with you. What is the feasibility of MDX support inside of the Kibana interface, so files matching the next docs spec can render without issue?

**Comment by spalger** [comment]
I think it's possible but we'd need to define support for all the default Components exposed by docsmobile to `.mdx` files, like `<DocLink />`, and a host of others... I could imagine docsmobile exposing a webpack loader or something which would power turning the `.mdx` file into a JS module which could be rendered in Kibana and include all the dependencies it needs but I don't think it's something we should expect any time soon.

**Comment by goodroot** [comment]
Thanks both! 

> @goodroot will internal links using markdown style syntax still be link checked?

1. Yes, eventually they will be checked whether they're doclinks or markdown links. Currently, only build-level checks on doclinks will create a failure.
2. In the future, link checks will not be a build failure condition. We'll report on them actively, and be prepared to fix them quickly, however we will not cause the condition to fail builds.

**Comment by bmorelli25** [comment]
Thanks, everyone! The more I dig into this, the more I realize our initial plan of building `readme.mdx` files by default (via `elastic-package build`) might not be an option—at least by itself. It’s likely part of a bigger solution. The three potential solutions I now see are:

#### (1) Add Kibana support for `.mdx` files and [Docsmobile](https://github.com/elastic/docsmobile):

Disclaimer: I’m a technical writer who knows nothing about what it would take to make this a reality. With that in mind, I believe this would be the best **long-term** solution for our users.

* Requirements:
  * Make `elastic-package` build `readme.mdx` files by default
  * Kibana adds support for `.mdx` files and docsmobile
* Pros:
  * No documentation constraints—the docsmobile project provides the tools we need to write great documentation without build constraints.
  * No building and maintaining multiple readme files.
  * Docs remain in Kibana and in our public documentation
* Cons:
  * Docsmobile project isn’t mature enough for this option (?)
  * Amount of Infra needed and coupling between the docs site and Kibana would be extreme (per @spalger’s comment above)

#### (2) Remove integration documentation from Kibana

Remove the docs from Kibana (as we know them today) and only show the following: Package title, description, screenshots, version, category, assets, features, and license. All of this content comes from the package manifest files and (if we update the package descriptions) could be enough to provide context and get a user started with an integration.
* Requirements:
  * Remove the logic that displays package readme files in Kibana.
  * Update to longer package descriptions (or add a new key in manifest)
  * Make `elastic-package` build `readme.mdx` files by default
  * (optional) eventually support `.mdx` and docsmoble in Kibana and re-add our docs to the product
* Pros:
  * The easiest option?
  * No documentation constraints—the docsmobile project provides the tools we need to write great documentation without build constraints.
  * No building and maintaining multiple readme files.
* Cons:
  * Removing in-product docs feels like a step backward as users have to leave the product for full context.

#### (3) Add [Docsmobile](https://github.com/elastic/docsmobile) support for `.md` files with frontmatter:

Like option one, but in reverse.
* Requirements:
  * Docsmobile adds support for `readme.md` files
  * Elastic packages builds `readme.md` with frontmatter from manifest files by default
* Pros:
  * No building and maintaining multiple readme files
  * Docs remain in Kibana and in our public documentation
  * Minimal updates required to package `readme.md` generation (just add frontmatter)
* Cons:
  * Constrained by the capabilities of markdown syntax—which isn’t the best for writing docs.
  * Unknown implementation difficulty on docsmobile side
  * A step backward?

**Comment by dedemorton** [comment]
Do we have any user feedback on the current approach (docs in Kibana + an external website)? It would be interesting to know whether users even _want_ in-product reference docs about integrations.

I prefer the 2nd approach as long as the docs in Kibana provide sufficient context so users understand what the integration provides and why to use it. I have a feeling that users probably don't navigate to the in-product instructions to view the reference content.

**Comment by colleenmcginnis** [comment]
>Remove integration documentation from Kibana

Another pro is that there may be some content that is relevant in the docs, but isn't relevant in Kibana. For example, [in the Cisco Meraki description](https://docs.elastic.co/integrations/cisco_meraki#enabling-the-integration-in-elastic) we provide instructions on how to get to the integration in Kibana. (And in the PRs addressing https://github.com/elastic/observability-docs/issues/1019 we point readers to the Getting started guide.) This kind of context is really helpful in the docs, but presumably the user has already completed these steps if they are reading it _in_ Kibana. 🙂 

<img width="883" alt="image" src="https://user-images.githubusercontent.com/10479155/170349591-04d6f565-7ce0-4fd5-b29f-66ffd2dd355e.png">

**Comment by bmorelli25** [comment]
Circling back to this thread. Thanks, DeDe and Colleen—those are good points.

I'm curious to hear what the integrations team thinks of the options listed above (https://github.com/elastic/observability-docs/issues/1848#issuecomment-1134994752).

**Comment by mtojek** [comment]
It looks like those ideas affect rather Fleet than elastic-package, so it might be good point to consult them with the Fleet team. cc @kpollich @joshdover

**Comment by joshdover** [comment]
> Do we have any user feedback on the current approach (docs in Kibana + an external website)? It would be interesting to know whether users even _want_ in-product reference docs about integrations.

My 2c here is that it's likely that most users who discover Fleet/Agent integrations via the UI probably don't know that the integration website even exists today, but if we linked out to it, maybe they would.

From a purely technical perspective, I much prefer not integrating Docsmobile into Kibana and maintaining another large dependency, especially considering that the docs website and packages can be released at any moment. We would need to be sure that older versions of Kibana always work with whatever embedded Docsmobile version they have given new package versions.

From a user's perspective, I think we do need to have some basic information about the package available directly in Kibana. There needs to be something useful and informative to help me understand if this package is going to solve what I need it to. That said, I don't think I've ever once used the reference information about which fields are present in the integration.

We also need to consider how we expect users in an air-gapped environment to use the docs website. I suspect that the end users likely do have direct access to elastic.co but this should be verified by product.

@mukeshelastic I believe you are the current owner for the integrations area. Do you have any thoughts about replacing the entire integration README in Kibana with a more basic description and linking out to the website for more information? This would help us get the docs website much more up to date than it is today. For example, the system integration hasn't had it's changelog published on the public website for many releases because this is not automated.

**Comment by bmorelli25** [comment]
Hi folks. @colleenmcginnis and I have put together a plan to address the problems plaguing our integration documentation and the scripts that we use to build it. Please take a look at this [Google Doc](https://docs.google.com/document/d/1ILw-qnl6bQH4f4s1tsKh5hthsDuwQnPV96IMASrEeWs/edit#heading=h.e8fq6tu86pe2) and comment with any feedback/concerns. Thanks!

**Comment by bmorelli25** [comment]
I'm going to close this issue as we have a well-defined path forward. Thanks for all of the input and ideas. Learn more about our next steps here: [https://github.com/elastic/integration-docs/issues](https://github.com/elastic/integration-docs/issues).
