### ISSUE TITLE
[META] Update tutorials to show Elastic Agent instead of Beats

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#2091]
## Description

All the [tutorials in the Observability Guide](https://www.elastic.co/guide/en/observability/current/observability-tutorials.html) show how to use Beats (Filebeat and Metricbeat) for monitoring. However now that Elastic Agent is GA, we need to update the tutorials. We also have cloud-native ways to send data (like the Elastic Serverless Forwarder) that we might want to cover in the tutorials.

Tutorials that require updates:

- [x] https://www.elastic.co/guide/en/observability/current/monitor-aws.html PR is up here: https://github.com/elastic/observability-docs/pull/2106
- [x] https://www.elastic.co/guide/en/observability/current/monitor-azure.html https://github.com/elastic/observability-docs/pull/2174
- [ ] #2972
- [ ] #2973
- [ ] #2974

Related issues:

- [x] https://github.com/elastic/observability-docs/issues/2251
- [ ] https://github.com/elastic/observability-docs/issues/2252

## Collaboration

- The docs team will lead producing the content

**Contact Person:**

TBD - varies by tutorial

## Suggested Target Release

8.4+

**Comment by dedemorton** [comment]
Met with Miguel to discuss K8s monitoring. The K8s tutorial will need to be rewritten, not just updated with Agent steps.

**Comment by dedemorton** [comment]
Closing this meta issue because this content no longer exists as tutorial info. plus there are other issues to track any required work.
