### ISSUE TITLE
7.11.0 Documentation Release

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#210]
### General release tasks

- [x] What's new in Observability 7.11
- [x] Stack docs copy of What's new
- [x] APM Server
  - [x] Release notes
  - [x] Breaking changes
  - [x] Upgrade guide
- [x] Beats
  - [x] Release notes
  - [x] Breaking changes
  - [x] Upgrade guide

### Brandon's list of tasks

- [x] Node.js agent dynamic updates https://github.com/elastic/apm-agent-nodejs/issues/1883 https://github.com/elastic/apm-agent-nodejs/pull/1975
- [x] Python agent "added in" https://github.com/elastic/apm-agent-python/issues/983 https://github.com/elastic/apm-agent-python/pull/984
- [x] Update agent instructions in the APM app https://github.com/elastic/kibana/issues/77739 https://github.com/elastic/kibana/pull/85855
- [x] [APM] Document known issue with Dependencies Table for RUM services https://github.com/elastic/kibana/issues/88202
- [x] Reupdate APM screenshots -- https://github.com/elastic/kibana/pull/88101 changed some of the terminologies used in the APM app. Screenshots + docs should be updated again
- [x] Working from https://github.com/elastic/beats/pull/23116, add application logging to the Filebeat quickstart. 
- [x] If ifdef/screenshots for videos: https://github.com/elastic/observability-docs/issues/323
- [x] Update APM Kubernetes content (if applicable)
