### ISSUE TITLE
Remaining doc issues to resolve for 7.10

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#235]
There are a few loose ends/feedback/cleanup required for 7.10. Creating this issue to track them

- [x] Finalize move to Fleet User Guide:
  - [x] Get all branches of docs building in the Fleet User Guide. https://github.com/elastic/docs/pull/2004 https://github.com/elastic/docs/pull/2004
  - [x] Set up redirects for ingest management > fleet (wildcard). https://github.com/elastic/website-www.elastic.co/issues/7066
  - [x] Remove the ingest management guide

- [x] Test steps (fleet and standalone) on deb/rpm. PRs: https://github.com/elastic/observability-docs/pull/244 and https://github.com/elastic/beats/pull/22562 https://github.com/elastic/observability-docs/pull/248

- [x] Verify upgrade changes here: https://github.com/elastic/beats/pull/22510/files/35ee1d26540a2d1a92875756c571c8d28c33685d..efff156e9abec9439d53c7b00a604d1d50aec467#diff-cb5a5af2dec36df51ec6cca4c8a87876483da9187609b28c0515056fdc6fbe39

- [x] Update links on the download page to the new URLs for Fleet docs. PR: https://github.com/elastic/website-www.elastic.co/issues/7091

- [x] After testing is complete, remove release-state override.

- [x] Make sure redirects are set up for any changed URLs. https://github.com/elastic/website-www.elastic.co/issues/7068

- [x] Add a better screenshot to show Fleet (one that shows multiple agents running).

- [x] Review feedback from @EricDavisX (mostly about upgrading):

````
FIXED
Agent upgrade points to make sure we have somewhere in the various documentation:
- for 7.10 'install' section we should probably the install with a note about manually stopping and removing any prior Agent deployed
- the 'upgrade' on the edge host for 7.10.0, is still a manual process (but different from what you have doc'ed I'll explain more).  In 7.10 we have introduced a new 'install' option as cited, which facilitates a persistent agent deployment for linux, macOS and Windows.
- Once the 7.10.0 or newer Agent is install, upgrading to subsequent versions can be done manually, like documented in 'install agent' or the user can be do this through the Kibana UI with a simple button click.
- From 7.10 and beyond, if the Kibana version is higher than the version of Agent then the Agent can be upgrade to the version of Kibana deployed.  
...In example, when a 7.10 patch comes out like 7.10.1, to upgrade Elastic Agent, the user can simply click the 'Upgrade agent' actions menu button in the 7.10.0 Fleet UI for the desired Agent.  Or the user may select multiple Agents and use the bulk actions menu to upgrade multiple agents at the same time.
-------------
FIXED there is a typo in the .rpm / .deb steps here: https://www.elastic.co/guide/en/ingest-management/7.10/elastic-agent-installation.html
elastic-agent enroll --kibana-url=KIBANA_URL --enrollment-token=ENROLLMENT_KEY
should be
elastic-agent enroll KIBANA_URL ENROLLMENT_KEY
... just like it was in 7.9 docs https://www.elastic.co/guide/en/ingest-management/7.9/run-elastic-agent.html
-------------
FIXED
- the 'upgrade-elastic-agent' page can be simplified with copy from the blurbs above.
https://www.elastic.co/guide/en/ingest-management/7.10/upgrade-elastic-agent.html
 - we can delete the edge host cli steps and just refer users to the 'install' steps (above) or the new UI based steps.
 - we can note again that 'Upgrade agent' is not enabled in the UI or supported for Agents deployed via .deb and .rpm artifacts.
 - we can NOTE: The 'Upgrade agent' action menu item is only enabled when the Kibana version is higher than the version of the Agent.

-------------

FIXED I have 2 more pages to do quick updates:
https://www.elastic.co/guide/en/ingest-management/7.10/uninstall-elastic-agent.html
this command must be called from the installed running agent… they won’t work if you use the location where you unzipped / untarr’ed the folder (which is not the final place where Agent puts the files, you see).
So we can change the commands for linux and macOS to remove the ./
easy.
and for windows, we can cite the full path to make it explicit:
C:\Program Files\Elastic\Agent\elastic-agent.exe uninstall

--------------
FIXED then reverted
and 2. on this page: https://www.elastic.co/guide/en/ingest-management/7.10/elastic-agent-cmd-options.html
we pulled support for ‘upgrade’ from the Agent command line, so we should take the whole section out.  I see it is still listed in the agent ‘help’ command so I’ll talk to Engineering about removing it. (edited) 
--------------

FIXED # 3) I believe we changed the kibana start up variables… from ‘ingestManager’ to ‘fleet’ now, see one legacy usage noted in: https://www.elastic.co/guide/en/ingest-management/7.10/fleet-troubleshooting.html
we should totally double check that if you aren’t sure, I’m totally not sure.
#4 on same page, I see a citation of ingest_manager in an api reference, that’s changed to ‘fleet’ now

--------------

FIXED - ok… about #2 see this issue.  I guess it should stay - but I never tested it as such, and I recall explicitly when we revoked support… it looks like it went back in but nobody talked about it to the group.  : /  communication is hard.  https://github.com/elastic/beats/issues/22530
````
