### ISSUE TITLE
[META]: Add cloud monitoring docs to the observability guide

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#2562]
## Problem description
The Infrastructure monitoring section of the Observability Guide has some problems:

* Focuses mostly on how to use the UI rather than end user goals.
* Content is stale and misleading. It recommends using Metricbeat and doesn't mention Elastic Agent.
* Current structure does not lend itself well to adding content about monitoring specific types of services and platforms, like AWS, K8s, and so on.

## Solution
To improve the docs, we need to:

```[tasklist]
### Tasklist for MVP (services identified as P0)
- [ ] https://github.com/elastic/observability-docs/issues/2548
- [ ] #2563
- [ ] https://github.com/elastic/observability-docs/issues/2546
- [ ] https://github.com/elastic/observability-docs/issues/2547
- [ ] https://github.com/elastic/observability-docs/issues/2557
- [ ] https://github.com/elastic/observability-docs/issues/2556
```

## Background on the google documents used to source the new content

To help improve the docs, the development team is creating a series of documents for our AWS integrations. Each document will:

* Introduce and describe of the service
* Show an image of our dashboard
* Describe the set of metrics that are key from monitoring perspective for this service.
* Explain why those metrics are key and how the current integration gathers and visualizes that data in the dashboard.
* Describe how users can extend the dashboard for more use cases as needed
* Link to integration, Agent, log monitoring etc. relevant documents for more details.

### Resources

https://github.com/elastic/obs-infraobs-team/issues/824
https://github.com/elastic/observability-docs/issues/2546
https://github.com/elastic/observability-docs/issues/2547
https://github.com/elastic/observability-docs/issues/2557
https://github.com/elastic/observability-docs/issues/2556

### Related PRs

https://github.com/elastic/observability-docs/pull/2564

### Collaboration

Other (please describe below in the Point of contact section).

### Point of contact.

Contacts are named in the related issues listed above.

**Comment by dedemorton** [comment]
Closing because new content is all merged and backported.
