### ISSUE TITLE
[Profiling] Move documentation to Elastic docs

### ISSUE THREAD

**Issue by mdbirnstiehl** [elastic/observability-docs#2614]
Connected to [2765](https://github.com/elastic/prodfiler/issues/2765).

This issue will move the Profiling docs from GitHub Pages to the Observability Docs.

**Phase one**
Create basic docs. These docs will disconnected from the doc build for this phase. 

I'm proposing the following structure for the documentation:

- Overview (when clicking Universal Profiling in the navigation menu) This would include the Features documentation currently in the GitHub Pages docs.
- Get Started (basic configuration to see data in Kibana (prereqs, enable in Kibana, host-agent deployment).
-  Advanced configuration. These would probably work best as individual sections. (Proxy, symbols for native frame, Split or filter data from multiple workloads).
- Upgrading
- Troubleshooting

**Phase two**
Once we have content we can move the docs to Elastic's doc build and publish:

- [ ]  Open a PR in elastic/docs to add to the build
- [ ]  Open infra ticket to add the elasticsearch/ci docs check to this repo
- [ ]  Add the elasticsearch/ci docs webhook to the repo
- [ ]  Add page header
- [ ]  Remove any remaining documentation content from readme and link to published docs

**Phase three**
Hook the Profiling docs into the rest of the Stack documentation. No list as docs change frequently, but inspiration can be taken from https://github.com/elastic/observability-docs/issues/383 and https://github.com/elastic/observability-docs/issues/792.

 Link from stack documentation to the Profiling documentation.

**Comment by bmorelli25** [comment]
Wow! This is going to be fun. I recently added the Android agent documentation to elastic.co/guide. This issue has a list of steps that you may find useful. Please reach out with any questions you have. https://github.com/elastic/apm-agent-android/issues/28

**Comment by mdbirnstiehl** [comment]
@bmorelli25 Could you take a look at this issue and see if there's anything I'm missing?

**Comment by iogbole** [comment]
LGTM,  thanks @mdbirnstiehl

**Comment by bmorelli25** [comment]
LGTM!

**Comment by inge4pres** [comment]
> Could you take a look at the suggested structure in Phase One of this issue.

Sounds good Mike, thanks 🙏🏼 
Where are we going to publish the docs?

**Comment by mdbirnstiehl** [comment]
> Where are we going to publish the docs?

@inge4pres It will be published in the [Observability Guide](https://www.elastic.co/guide/en/observability/current/index.html). 

As long as we are ok to move the content in your 8.7 branch in the current profiling docs to the main documentation, I will use that content for this process.

**Comment by inge4pres** [comment]
Thanks for the clarification.

One note: there is an unfinished part in the [intended user docs for 8.7](https://github.com/elastic/universal-profiling-documentation/tree/update-8.7).
We still don't have a link for the symbolization binary, and instructions on how to make it work properly are incomplete.

Can you please leave out that section from bullet point 3 of phase one until we fix that?
Thanks 🙏🏼

**Comment by inge4pres** [comment]
> Can you please leave out the "Add symbols for native frames" section from bullet point 3 of phase one until we fix that? Thanks 🙏🏼

@mdbirnstiehl this commit adds back native frames symbolization.
https://github.com/elastic/universal-profiling-documentation/commit/1c48a6804cca7c2ff27c3ec08b98e5c6c916c47f

Can yo please proof-read and possibly include in 8.7 guides? 🙏🏼
