### ISSUE TITLE
[REQUEST]: Move ESF docs to a separate repo with accurate versioning and create a new "book"

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#2716]
### Description

Right now the [docs for the Elastic Serverless Forwarder](https://www.elastic.co/guide/en/observability/current/aws-elastic-serverless-forwarder.html) follow the stack versioning scheme, which is confusing to users because the code follows a different versioning scheme. 

To fix this problem, we should move the ESF docs out of the observability-docs repo and make the ESF docs a separate "book" with versioning that matches the software release versions.

To do this, we need to add branches to the existing elastic-serverless-forwarder repo or create a new repo called something like elastic-serverless-forwarder-docs

Note that we currently provide ESF docs in version 7.16 and later.

### TODO

- [x] Create new repo or branches in existing repo.
- [x] Copy files to new location and create a new book structure.
- [ ] Decide how to handle links to the plugin docs. We might want ESF docs to use a conditional to link to the VPR page for versions lower than 8.7.
- [x] Decide whether to create doc branches for _every_ doc version or just the versions going forward. If we create doc branches for all versions, we'll also need to fix the markdown files.
- [ ] Update conf.yaml to pull files from new repo and build separate guide.
- [ ] Update cross-doc links.
- [ ] Set up redirects for old URLs to new URLs.
- [ ] Delete old ESF files (if we decide to put all versions in one "book")

### Resources

n/a

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @dedemorton 

**Stakeholders:** users

**Comment by dedemorton** [comment]
Capturing comment from slack thread about creating doc branches in the existing LSF repo from @aspacca:

I have no problem to create branches for docs, one for each version, in the ESF repo. I'd still need to create tags for the releases. every tag will be final and reference a specific commit of the docs "folder", but since the tag it's used only for the deployment script it will just ignore everything that's not code/LICENSE.txt/README.md for the AWS Serverless Application Repository details page

....not sure if we will create the first branch as the first new version of ESF once we are ready with the separated guide, or we want to make the effort to create an history for older version. since 23rd Nov 2022 the content already exists in the observability-docs repo, and we can track the versions history. previous one should be "ported" from markdown that was present in the ESF repo to asciidoc.

**Comment by dedemorton** [comment]
## Pros/cons of all versions in the LSF "book":

**Pros:** 
* Users would be able to switch easily between versions.
* There would be no ambiguity about where the content lives. The redirect strategy would be fairly straightforward and the same for all versions.
* Easier for contributors to figure out where the source files live.

**Cons:**
* We lose contribution history (kind of big drawback IMO).
* May affect SEO for awhile. Not sure if redirecting the existing content would help or hurt SEO.
* Would require some extra work to fix readme files.

## Pros/cons of including new versions only:

**Pros:**
* Less work up front because we wouldn't have to move old files or fix doc links in old versions.
* Would help us avoid confusing existing users who know to look for the content in the obs guide.

**Cons:**
* Potentially confusing experience for users who end up in the wrong version and need to navigate to the new version (or vice versa).
* Extra work to add banners or some other mechanism to alert users to the existence of the new book for new versions.

**Comment by dedemorton** [comment]
@aspacca A couple of related questions:

* Does each LSF version map to a specific stack version? 
* Are their changes in functionality from version to version that we need to take into consideration or are the docs basically the same across all versions?
* If the same, will this change in the future?

**Comment by bmorelli25** [comment]
I'm curious to hear the answers to DeDe's follow-up questions. In the meantime, I'd vote for only including new versions. It is a potentially confusing experience for users initially, but that quickly disappears as newer versions are released (and it looks like new versions are released often). I'm also not sure the benefits of adding all versions outweigh the time commitment required to do so.

**Comment by aspacca** [comment]
> ## Pros/cons of all versions in the LSF "book":
> **Pros:**
> * There would be no ambiguity about where the content lives. The redirect strategy would be fairly straightforward and the same for all versions.

for me this is a Pro that's still true even in the case "of including new versions only"

my assumption is that, regardless we publish all version in the ESF "book" or new versions only, we'll remove the existing docs, and only the new "book" will exists

> ## Pros/cons of all versions in the LSF "book":
> Cons:
> We lose contribution history (kind of big drawback IMO).

there are mitigation for this: what is the major factor in considering it a drawback? is it about tracking how the content evolved or about attribution of the contributions?
in the first case, while a little annoying, I volunteer to recreate the equivalent commit history so to track the evolution of the content

beware that I have the impression that, once in a dedicated "book", the organisation and the content might change, to fit better ESF, rather than what we have now that was more constrained to fit the destination of the ESF docs.
from this point of view the contribution history loss is much less relevant in my opinion, since we are anyway producing (hopefully :)) better docs





> ## Pros/cons of including new versions only:
> **Cons:**
> * Potentially confusing experience for users who end up in the wrong version and need to navigate to the new version (or vice versa).

this is true for every "book", not specific to ESF, isn't it?
and also in the case we publish all version of ESF in the new "book"
when I look at ES docs, I have to care about the version of the documentation I've selected.
still I have this option: currently ESF docs publicly available is only latest, I have no way to access the docs of the version I've deployed if I've not upgraded to the latest one

**Comment by aspacca** [comment]
> * Does each LSF version map to a specific stack version?

there are totally unrelated, similarly to the versions of an integration package.
still an ESF version support up to a minimum version of the stack, and each stack "component" (ie: elasticsearch vs logstash) might have different minimum versions, or being supported through different ESF version (for example logstash support was added just in v1.7.0 of the ESF)

moreover: currently ESF is only on AWS, tomorrow it could be on GCP and AZURE, and on each cloud provider have different supported stack components and versions of each component
on each cloud provider the features supported could vary as well

this is something to address since the beginning in the new "book" in my opinion: organising the content according to each cloud provider (while for the moment and probably in the nearby future, we'll still have AWS only).
regarding to this specific point: on each cloud provider  the ESF can "look" totally different from the point of view of an user, the "s3 config file" for sure won't exists in Azure and GCP, for example. we'll try our best to make as much coherent as possible the experience across every provider, but it's something we don't have total control on (indeed there's little we can do: we just have to adapt to what the cloud provider serverless solution offers=

> * Are there changes in functionality from version to version that we need to take into consideration or are the docs basically the same across all versions?

There are changes in functionality, as well the topic about the different functionalities we'll have in the future on different cloud provider
We try to not introduce breaking change (we did one or two before v1 release), and if we are forced to, we'll bump the major version.

the change in functionality until now where specific related to the ESF versions, and not linked to any version of the stack (but for introducing support of logstash): this means that if we introduce a new functionality we try to not bump the minimum compatible version of the stack components we support. this was always true until now, and I don't see it something the I'd expect to change, but it could happen in the future that we might not be able to add a new functionality keeping the backward compatibility of matrix of the stack components.

what happen can be as well that we will support a functionality of specific stack component version, since a specific ESF version, only if the users have ESF "talking" with that specific stack component version: imagine ESF v1.8.0 supporting a specific feature of ES 8.8 if that's the version it forwards event to but not in the case the user forward to ES <8.8

> * If the same, will this change in the future?

it's not the same :)
but even if it they would be the same, that would be true only for ESF on AWS. as mentioned above

**Comment by dedemorton** [comment]
@aspacca Thanks for all the details. I'm more concerned about attribution of the contributions than capturing the history of how the content evolved. 

So based on the discussion here, sounds like we should:

* Create a new book for the ESF docs that contains new versions only.
* Delete the existing ESF content from the Observability Guide (all versions?)

If this is correct, I'll update my task list and assign owners.

It sounds like @aspacca should be responsible for making a copy of the latest files and moving them to a docs directory in the ESF repo. Once the files are there, we can do our magic to get the new content building and delete the old files in the observability docs repo. We'll need to coordinate the timing of this. Probably after 8.7 because we're running out of road.

Sound good?

**Comment by aspacca** [comment]
> It sounds like @aspacca should be responsible for making a copy of the latest files and moving them to a docs directory in the ESF repo

done https://github.com/elastic/elastic-serverless-forwarder/pull/270/commits

I've cherry-picked all the commits in the original PRs related to ESF: this way we kept both commits history and attributrions
it was not always possible since some commits belong to branch that were deleted in the meanwhile, and I applied directly a patch: in this case the changes are attributed to me
