### ISSUE TITLE
[Meta] Improvements to APM documentation 

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#2926]
```[tasklist]
### Needs stakeholder feedback
- [ ] https://github.com/elastic/apm-server/pull/10750
```

```[tasklist]
### Changes
- [ ] https://github.com/elastic/apm-server/pull/10751
- [ ] https://github.com/elastic/apm-server/pull/10772
```
