### ISSUE TITLE
Add guide about monitoring cloud services

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#299]
Meta issue to track guides about monitoring cloud services and other orchestrators / platforms:
- [x] Kubernetes https://github.com/elastic/observability-docs/pull/151
- [x] AWS https://github.com/elastic/observability-docs/pull/610
- [x] Azure https://github.com/elastic/observability-docs/pull/615
- [ ] Cloud Foundry
- [x] GCP https://github.com/elastic/observability-docs/pull/423
- [ ] vSphere

Completed guides live [here](https://www.elastic.co/guide/en/observability/current/observability-tutorials.html).

**Comment by EamonnTP** [comment]
@andresrc @dedemorton @bmorelli25 Do we want to prioritise which services we want to document? 

- AWS
- Azure
- Cloud Foundry
- GCP
- vSphere

**Comment by dedemorton** [comment]
Good question. We should get input from product marketing and perhaps the support team to see where the need is the greatest and prioritize accordingly.

I think the education team is already working on a guide for AWS. We should coordinate with @melvynator.

**Comment by melvynator** [comment]
We are currently working on 2 guides:
- GCP
- AWS

If these POCs are successful I would like to prioritize Azure. But Vsphere is also a request that I have received.

I have a meeting with the PM/PMM team to give them an update on the work we have been doing with regards to quick starts, guides, and the short-form videos, if you would like I can try to gather some of their inputs.

**Comment by joshuastepp** [comment]
@jmikell821 @nastasha-solomon - for your tracking

**Comment by dedemorton** [comment]
Closing because this issue was used to track old work.
