### ISSUE TITLE
Create an end-to-end flow of taking a log file from disk to Elastic

### ISSUE THREAD

**Issue by mdbirnstiehl** [elastic/observability-docs#3001]
This documentation should follow the journey of a log file to Elastic including accomplishing the following:

- Stream your log data - get log files into Elastic. This section will show users how to accomplish everything that's in the new onboarding process in Logs+ without using the UI. 
- Query your log data - Make sure users have the basics of being able to query log data.
- Enhance your log data - improve your ability to query log data, including parsing, routing, and mappings.
- Implement Integrations - show users how to use integrations to get the most out of their experience.

### Google doc to work from
[Google doc](https://docs.google.com/document/d/1kEupX7cmAx2VEUNfGn8JbZ0n1tRQtiCOjUY1fkJJrVg/edit?usp=sharing) to allow for collaboration.

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/observability-docs/issues/3037
- [ ] https://github.com/elastic/observability-docs/issues/3015
- [ ] https://github.com/elastic/observability-docs/issues/3010
- [ ] https://github.com/elastic/observability-docs/issues/3012
```

**Comment by ruflin** [comment]
I think what you have above is all together an end to end flow that can be split up into mutliple parts. The way I think of it is:

* User starts with collecting logs -> streaming log files
* Queries the the data -> for this some basic data stream understanding is needed, is this also working with unstructured data?
* Adds more specific mappings -> Mapping
* Processes the data -> Ingest pipelines -> parse
* Can use integrations to get the full experience -> integrations

Overall, it is one story with several chapters. Whatever stage the user is in already, they can jump directly to section that fits them. The titles of the "chapters" should be related to the problems the user is facing, like "Parse your logs". "Data streams" is a technical concept the user might have to learn about but is not why they come to the docs in the first place.

I'll comment with further details on the Google docs but I would like to see the order and titles slightly changed to have it more focused on user problems then explaining technologies.
