### ISSUE TITLE
Create Operations Logs Guide

### ISSUE THREAD

**Issue by mdbirnstiehl** [elastic/observability-docs#3098]
## Operations Guide

The Operations Guide should contain the following sections

- [Collect logs](https://docs.google.com/document/d/1CXwzftd_GJHYSVSfKhLWJZTRyH-vT1OKN6eFkxKbKy4/edit#heading=h.9b2t8y29cq69)
- [Organize logs](https://docs.google.com/document/d/1P3D4bhpUP_dMzbIu9r3T2k8G83xqVsnv2nM_HCtn7KY/edit?usp=sharing)
   - Mappings
   - Pipelines & Routing
   - Data stream/dataset
   - Life cycle
- [Work with logs](https://docs.google.com/document/d/1UT1tdKEEzmSHDdOV4xqLLtcBlgCSQuRMffpFfBNz9yM/edit?usp=sharing)
   - Explore (discover) Search and Stream
   - Alerting
   - SLOs
   - AIOps
- [Combine with observability data](https://docs.google.com/document/d/13w5cEZS2keEs-H5hjlmbFRRcjs1zHx9MKhVKUxgeeJA/edit?usp=sharing)
   - Traces
   - Metrics
- [Examples](https://docs.google.com/document/d/1HvM5IWTzq6ezM7ueAw3XWpxj9JqdRxzMjIixssTQnt4/edit?usp=sharing)

## Milestones:

- [x] Set up the docs - due 7/24
- [x] Add questions each section should answer - due 7/24
- [x] Add relevant blogs and docs links - due 7/24
- [ ] Compile information - due 7/31
- [ ] Get reviewers - due 7/31
