### ISSUE TITLE
Create a "Get the most out of your log data" section

### ISSUE THREAD

**Issue by mdbirnstiehl** [elastic/observability-docs#3115]
### Summary
Create a story based off of [this document](https://docs.google.com/document/d/1QyB3P3jFKp3iFUJQ6MttC2YtUrhhZZhVn4CZRUrJAlQ/edit#heading=h.anrvn3dmntty) detailing how users can get more value out of their logs data once it's in Elasticsearch. 

The goal is to focus on what users want to accomplish, and not on the intricacies of our concepts. 

Initially, this will be documented on the [Stream a log file](https://www.elastic.co/guide/en/observability/current/logs-stream.html) page. 

### Story topics

Each topic should be a standalone section. A user can come to this document if they want to extract a specific field from their log data, or if they are starting from the very beginning.

See the following tasks for topics:

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/observability-docs/issues/3119
- [ ] https://github.com/elastic/observability-docs/issues/3120
- [ ] https://github.com/elastic/observability-docs/issues/3121
- [ ] https://github.com/elastic/observability-docs/issues/3122
- [ ] https://github.com/elastic/observability-docs/issues/3124
- [ ] https://github.com/elastic/observability-docs/issues/3125
- [ ] https://github.com/elastic/observability-docs/issues/3126
```
