### ISSUE TITLE
Add Monitoring Kubernetes User Flow

### ISSUE THREAD

**Issue by mdbirnstiehl** [elastic/observability-docs#3368]
We currently have a tutorial on [monitoring K8s](https://www.elastic.co/guide/en/observability/current/monitor-kubernetes.html).

This information appears to need some updating (focuses on beats, no integrations, etc.). Also need to decide if we want to pull the logs info from these docs. 

Depending on the scope of this issue, updating the logs to use agent would probably mean that metrics and the rest of the doc should also be updated to use agent. 

This [document](https://docs.google.com/document/d/18DyRYhw9Rg6JbPlC2yp20l2EwoE1fUq3NtyIlLnuYmw/edit) poses some questions and will ultimately outline the path forward. 
```[tasklist]
### Tasks
- [x] Update the overview page
- [x] Update the monitoring page (add integration info).
- [x] Update the application monitoring page
- [x] Update descriptions in integration UI.
```
