### ISSUE TITLE
Documenting rate aggregation for the new custom threshold rule

### ISSUE THREAD

**Issue by maryam-saeidi** [elastic/observability-docs#3530]
### Description

We are introducing **rate** aggregation to the `custom threshold` alerting rule in this [PR](https://github.com/elastic/kibana/pull/173728). (To check this aggregation, you need to create a custom threshold rule from Observability > Alerts > Create rule > Custom threshold (Beta) and select `rate` aggregation)

This logic is similar to rate aggregation in the `metric threshold` alerting rule, and based on some questions (like this [one](https://elastic.slack.com/archives/C04S4RWV2M6/p1703660821678909)) it is not clear how this aggregation works behind the scene. So, we would like to share more information through documentation and possibly include a link in the rule creation flyout when rate aggregation is selected, something like:

<img src="https://github.com/elastic/observability-docs/assets/12370520/fe64b40d-a95e-42d5-8b55-4c63088cfe8e" width=300 />

### Information that can be useful to our users
We want to make sure we explain (1) how the rate is calculated and also (2) what the number shown on the preview chart means. ([example](https://elastic.slack.com/archives/C04S4RWV2M6/p1703678319854449?thread_ts=1703660821.678909&cid=C04S4RWV2M6))

The rate is calculated as follows: ([code](https://github.com/elastic/kibana/pull/173728/files#diff-b3675c41cd8592cab279989084bf6f78b0325532f42d196921aae4841356b185R25))
```
params.second > 0.0 && params.first > 0.0 && params.second > params.first ? (params.second - params.first) / ${intervalInSeconds}
```
Where first is the max value of the selected field in the **previous** bucket, and second is the maximum value for the **current** bucket.
The number shown on the preview chart is, therefore, the difference between the second and first bucket divided by the number of seconds in the selected interval.

#### Tasks
- [x] Create a dedicated section/page for rate aggregation + example
- [x] Add rate and percentile aggregations to the list of custom threshold aggregations (related [comment](https://github.com/elastic/staging-serverless-observability-docs/pull/222#pullrequestreview-1924978998))
        <img src="https://github.com/elastic/observability-docs/assets/12370520/4d9b6043-8b25-4472-af79-f62cd590f4f7" width=500 />
- [x] Custom threshold rule has a different header than other rules

| Custom threshold | Inventory |
|---|---|
|![image](https://github.com/elastic/observability-docs/assets/12370520/57a03495-979c-4cd1-a2b5-ff3e7661598a)|![image](https://github.com/elastic/observability-docs/assets/12370520/b158f034-11f9-4a90-bb09-6f8d5bcf454b)|

### Resources

PR: https://github.com/elastic/kibana/pull/173728

### Which documentation set does this change impact?

Stateful and Serverless

### Feature differences

The feature is identical in Stateful and Serverless.

### What release is this request related to?

8.13

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @maryam-saeidi 

**Stakeholders:**
- @paulb-elastic
- @vinaychandrasekhar

**Comment by bmorelli25** [comment]
@maryam-saeidi will this go into Serverless before the 8.13 release?

**Comment by paulb-elastic** [comment]
If the docs are not ready, then merging the [PR](https://github.com/elastic/kibana/pull/173728) when it's ready (without the link) is a good idea @maryam-saeidi (to decouple them).

If we follow up with a separate PR for the docs link, then I'd suggest ensuring it also makes 8.13, so we're not releasing the stateful version without the docs link.

**Comment by dedemorton** [comment]
@maryam-saeidi I have a quick question about your request to:

>Create a dedicated section/page for rate aggregation + example

You say that the logic for the rate aggregation in the custom threshold rule is _similar_ to rate aggregation in the metric threshold rule. Is the logic similar enough that it makes sense to create a separate/dedicated page that covers rate aggregation for both types of rules? So we would have a page that:

* Explains why you would use rate instead of average for something like a counter.
* Shows how the rate is calculated.
* Provides a realistic example.

And then we could point to the page from both rules. The other option is to provide a section or block in the custom threshold rule docs that explains these concepts.

I'm actually pretty new to a lot of these concepts, so my apologies if I'm getting things wrong.

**Comment by maryam-saeidi** [comment]
> Is the logic similar enough that it makes sense to create a separate/dedicated page that covers rate aggregation for both types of rules?

@dedemorton Yes! I like the idea of having a dedicated page and linking it to both rules.
No worries, I am also learning more about this aggregation through examples that other developers provide, so we can learn together! :D

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/observability-docs/pull/3676 and  https://github.com/elastic/staging-serverless-observability-docs/pull/241/
