### ISSUE TITLE
7.12 Documentation release

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#371]
### General release tasks

- [x] What's new in Observability 7.11
- [x] Stack docs copy of What's new
- [x] Stack docs copy of BC https://github.com/elastic/stack-docs/pull/1613
- [x] APM Server https://github.com/elastic/apm-server/pull/4959
  - [x] Release notes 
  - [x] Breaking changes
  - [x] Upgrade guide
- [x] Beats
  - [x] Release notes
  - [x] Breaking changes
  - [x] Upgrade guide

### Other

- [x] PHP documentation updates: https://github.com/elastic/observability-docs/issues/383
- [x] Data streams: https://github.com/elastic/observability-docs/issues/388
- [x] APM Server package https://github.com/elastic/observability-docs/issues/273
- [x] Remove contextual filter documentation https://github.com/elastic/kibana/issues/92954 https://github.com/elastic/kibana/pull/94446
