### ISSUE TITLE
PHP agent documentation updates

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#383]
## Summary

PHP agent documentation links and/or content needs to be added to the following locations:

### Observability Guide
- [x] [Instrument apps](https://www.elastic.co/guide/en/observability/7.11/instrument-apps.html) 
- [x] [Monitor Kubernetes](https://www.elastic.co/guide/en/observability/7.11/monitor-kubernetes.html#monitor-kubernetes-application-performance)

### APM Overview
- [x] [Components](https://www.elastic.co/guide/en/apm/get-started/7.11/components.html)
- [x] [Quick start](https://www.elastic.co/guide/en/apm/get-started/7.11/install-and-run.html)
- [x] [Dropped spans](https://www.elastic.co/guide/en/apm/get-started/7.11/transaction-spans.html#dropped-spans)
- [x] [SetLabel/SetContext/SetUser](https://www.elastic.co/guide/en/apm/get-started/7.11/metadata.html#metadata) Marked as _coming soon_.
- [x] [Distributed tracing:](https://www.elastic.co/guide/en/apm/get-started/7.11/distributed-tracing.html)  `traceparent` compatibility and manual tranceparent propagation
- [x] [Transaction sample rate config](https://www.elastic.co/guide/en/apm/get-started/7.11/trace-sampling.html)
- [x] [Agent/Server compatibility](https://www.elastic.co/guide/en/apm/get-started/7.11/agent-server-compatibility.html)
- [x] [Troubleshooting](https://www.elastic.co/guide/en/apm/get-started/7.11/troubleshooting.html)
~- [ ] [Metrics](https://www.elastic.co/guide/en/apm/get-started/7.11/metrics.html)~
~- [ ] [OpenTracing Bridge](https://www.elastic.co/guide/en/apm/get-started/7.11/opentracing.html)~

### APM Server Reference
- [x] [Set up](https://www.elastic.co/guide/en/apm/server/current/next-steps.html)
- [x] [Server cert/pinning](https://www.elastic.co/guide/en/apm/server/current/ssl-setup.html)
- [x] [API keys](https://www.elastic.co/guide/en/apm/server/current/api-key.html)
- [x] [Secret token and serverURLs](https://www.elastic.co/guide/en/apm/server/current/secret-token.html)
- [x] [Troubleshooting](https://www.elastic.co/guide/en/apm/server/current/troubleshooting.html)

### Kibana Reference
- [x] [Service maps supported version](https://www.elastic.co/guide/en/kibana/current/service-maps.html)
- [x] [Central config support](https://www.elastic.co/guide/en/kibana/current/agent-configuration.html)
- [x] [Service environment filter](https://www.elastic.co/guide/en/kibana/current/filters.html#environment-selector)
- [x] [Troubleshooting](https://www.elastic.co/guide/en/kibana/7.11/troubleshooting.html)

### In product
- [x] APM agent setup instructions https://github.com/elastic/kibana/pull/91381

## Implementation PRs

- [ ] docs: Add PHP agent information to shared docs elastic/apm-server#4740
- [x] docs: add boilerplate troubleshooting topic elastic/apm-agent-php#352
- [x] docs: add PHP agent info to k8s tutorial #393
- [x] docs: Add PHP agent information to docs https://github.com/elastic/kibana/pull/91773

**Comment by bmorelli25** [comment]
@SergeyKleyman FYI I created a list of everywhere that agent content is included in the four main Observability documentation books. I'll start going through and adding content in, but I'll likely have questions for you on some of these.

**Comment by SergeyKleyman** [comment]
@bmorelli25 Thank you for keeping me up to date. I assume you refer in part to what I mentioned at https://github.com/elastic/apm-agent-php/issues/347, am I correct?

**Comment by bmorelli25** [comment]
Oh wow, we each had the same thought 😅. Should I just move all of these links into your issue and close this one out?

**Comment by SergeyKleyman** [comment]
> Should I just move all of these links into your issue and close this one out?

Whatever is more convenient for you since you are the one that is going to do all the work :)

**Comment by SergeyKleyman** [comment]
@bmorelli25 It seems everything is done, doesn't it?

**Comment by bmorelli25** [comment]
Indeed! Closing this out.
