### ISSUE TITLE
Fleet Server scaling and deployment guidelines

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#523]
We need a guide for users who are responsible for operating Fleet Server. It should describe:

- [x] how to observe Fleet Server and know when to scale it https://github.com/elastic/fleet-server/issues/173
- [x] how to scale it https://github.com/elastic/fleet-server/issues/185
- [x] scaling limits https://github.com/elastic/fleet-server/pull/240
- [x] scaling guidance for ESS instance types https://github.com/elastic/fleet-server/issues/134

**Comment by dedemorton** [comment]
Another related issue: https://github.com/elastic/fleet-server/issues/416

**Comment by EricDavisX** [comment]
We decided to close out the above issue and document the nuance that we expect all Fleet Servers in production to use full TLS and that we don't support a mixed environment.

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/observability-docs/pull/1061
