### ISSUE TITLE
Fleet Settings

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#525]
We should document the Fleet Settings for Fleet Server and Elasticsearch hosts. We'd like to add links to the docs from the product https://github.com/elastic/kibana/issues/96208. 

- [x] What are these settings
- [x] Why users need to set them
- [x] How to set them https://github.com/elastic/kibana/issues/94624
- [ ] The defaults for protocol and ports
- [ ] How to enter IPv6
- [x] What happens if there are multiple https://github.com/elastic/kibana/issues/89442
- [ ] What a default Fleet server is
- [ ] What happens if they set it wrong and how to fix it https://github.com/elastic/beats/issues/24739

See example from Filebeat https://www.elastic.co/guide/en/beats/filebeat/7.x/filebeat-reference-yml.html

    # Array of hosts to connect to.
    # Scheme and port can be left out and will be set to the default (http and 9200)
    # In case you specify and additional path, the scheme is required: http://localhost:9200/path
    # IPv6 addresses should always be defined as: https://[2001:db8::1]:9200
