### ISSUE TITLE
Quality fixes for observability and related docs

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#531]
Task list for general quality improvements to Observability and related docs. This list contains some links to issues tracked in the Beats repo:

- [ ] Proofread the Observability Guide: https://github.com/elastic/observability-docs/issues/529
- [ ] Proofread the Fleet User Guide: https://github.com/elastic/observability-docs/issues/530
- [ ] Validate and fix jump lists in the Beats documentation: https://github.com/elastic/beats/issues/25120

**Comment by dedemorton** [comment]
@leahleahy I'm closing this issue because we no longer want you to proofread the Obs or Fleet User Guide. Instead I will assign a testing issue.
